// Generated by https://quicktype.io

import { UserProduct } from './product.model';

export interface CategoriesResponse {
  total: number;
  categorias: Category[];
}

export interface Category {
  _id: string;
  nombre: string;
  usuario: UserProduct;
}
